#ifndef BRUTAL_UAPI_H
#define BRUTAL_UAPI_H

#include <linux/types.h>

#define TCP_BRUTAL_PARAMS 23301
#define TCP_BRUTAL_VERSION 23302
#define TCP_BRUTAL_INFO 23303

#define BRUTAL_INFO_ABI_V1 1
#define BRUTAL_VENDOR_UPSTREAM 0
#define BRUTAL_VENDOR_CUSTOM 1
#define BRUTAL_BUILD_ID_LEN 40

#define BRUTAL_CAP_PERIP (1ULL << 0)
#define BRUTAL_CAP_NETNS (1ULL << 1)
#define BRUTAL_CAP_EXACT_RULE_HASH (1ULL << 2)
#define BRUTAL_CAP_PEER_STATS (1ULL << 3)
#define BRUTAL_CAP_TC_AGGREGATE_MANAGER (1ULL << 4)
#define BRUTAL_CAP_PEER_BUDGET (1ULL << 5)
#define BRUTAL_CAP_PREFIX_INDEX (1ULL << 6)
#define BRUTAL_CAP_KERNEL_AGGREGATE (1ULL << 7)
#define BRUTAL_CAP_GENL (1ULL << 8)

struct brutal_info_v1
{
    __u16 size;
    __u16 abi_version;
    __u32 vendor_id;
    __u32 version;
    __u32 flags;
    __u64 capabilities;
    __u8 build_id[BRUTAL_BUILD_ID_LEN];
} __attribute__((packed));

#define BRUTAL_GENL_NAME "tcp_brutal"
#define BRUTAL_GENL_VERSION 1

enum brutal_genl_command
{
    BRUTAL_CMD_UNSPEC,
    BRUTAL_CMD_GET_INFO,
    BRUTAL_CMD_GET_STATS,
    BRUTAL_CMD_RULE_GET,
    BRUTAL_CMD_RULE_DUMP,
    BRUTAL_CMD_RULE_ADD,
    BRUTAL_CMD_RULE_DEL,
    BRUTAL_CMD_PEER_GET,
    BRUTAL_CMD_PEER_DUMP,
    BRUTAL_CMD_LIMIT_GET,
    BRUTAL_CMD_LIMIT_SET,
    BRUTAL_CMD_EVENT,
    __BRUTAL_CMD_MAX,
};
#define BRUTAL_CMD_MAX (__BRUTAL_CMD_MAX - 1)

enum brutal_genl_attribute
{
    BRUTAL_A_UNSPEC,
    BRUTAL_A_ABI_VERSION,
    BRUTAL_A_VENDOR_ID,
    BRUTAL_A_VERSION,
    BRUTAL_A_FLAGS,
    BRUTAL_A_CAPABILITIES,
    BRUTAL_A_BUILD_ID,
    BRUTAL_A_FAMILY,
    BRUTAL_A_PREFIX_LEN,
    BRUTAL_A_ADDRESS,
    BRUTAL_A_RULE_ID,
    BRUTAL_A_RATE,
    BRUTAL_A_AGGREGATE_RATE,
    BRUTAL_A_CWND_GAIN,
    BRUTAL_A_LOCKED,
    BRUTAL_A_PERIP,
    BRUTAL_A_MAX_PEERS,
    BRUTAL_A_MEMBERS,
    BRUTAL_A_ACTIVE_PEERS,
    BRUTAL_A_SENT_BYTES,
    BRUTAL_A_PEER_ALLOC_FAILURES,
    BRUTAL_A_PEER_INSERT_FAILURES,
    BRUTAL_A_PEER_FALLBACKS,
    BRUTAL_A_PEER_BUDGET_FALLBACKS,
    BRUTAL_A_PEER_SLOTS,
    BRUTAL_A_PEAK_PEER_SLOTS,
    BRUTAL_A_PEAK_PEERS,
    BRUTAL_A_OVERFLOW_POLICY,
    BRUTAL_A_EVENT_TYPE,
    __BRUTAL_A_MAX,
};
#define BRUTAL_A_MAX (__BRUTAL_A_MAX - 1)

enum brutal_overflow_policy
{
    BRUTAL_OVERFLOW_HASHED_FALLBACK = 1,
};

enum brutal_event_type
{
    BRUTAL_EVENT_RULE_ADDED = 1,
    BRUTAL_EVENT_RULE_UPDATED,
    BRUTAL_EVENT_RULE_DELETED,
    BRUTAL_EVENT_LIMIT_CHANGED,
};

#endif
